# ContractGuard AI — Executed Capstone Evidence

**Program:** SDAIA Academy — Advanced Agentic AI Systems Engineering  
**Cohort/session:** June 2026  
**Project:** Secure Multi-Agent Vendor Contract Audit Platform

This notebook executes and preserves evidence for all six rubric deliverables: real tool
use and named reasoning patterns, framework-managed graph orchestration, role-specialized
agents, security and observability, durable checkpoint/HITL/cloud artifacts, and
professional documentation.

In [1]:
from pathlib import Path
import json, os, subprocess, sys
import pandas as pd
from IPython.display import display, Markdown

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == 'notebooks':
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT / 'src'))
print('Project root:', PROJECT_ROOT)
print('Python:', sys.version.split()[0])

Project root: /mnt/data/contractguard-ai
Python: 3.13.5

## 1. Execute the complete security, retry, HITL, restart, and output-validation demonstration

The runner contains hard assertions. Any missing rubric behavior causes the cell to fail.
It executes a real prompt-injection attack, a safe contract, a high-risk contract with a
simulated tool timeout, a Reflexion re-search loop, a durable human interrupt, a fresh
service restart, human approval, an output-schema revision loop, PII masking, and artifact
storage.

In [2]:
result = subprocess.run(
    [sys.executable, str(PROJECT_ROOT / 'scripts' / 'run_capstone_demo.py')],
    cwd=PROJECT_ROOT,
    text=True,
    capture_output=True,
    check=True,
)
print(result.stdout)
if result.stderr:
    print('STDERR:', result.stderr)

[1/6] Running real prompt-injection attack attempt...
[2/6] Running low-risk happy path...
[3/6] Running tool-failure retry, Reflexion, and HITL pause paths...
[4/6] Closing the process and proving durable restart recovery...
[5/6] Resuming from the human approval interrupt...
[6/6] Writing an evaluator-friendly execution summary...
{
  "prompt_injection_was_blocked": true,
  "tool_failure_retry_fired": true,
  "quality_replan_loop_fired": true,
  "persistent_checkpoint_survived_restart": true,
  "human_pause_resumed": true,
  "output_validation_revision_fired": true,
  "pii_was_masked": true,
  "structured_logs_exist": true,
  "prometheus_metrics_exist": true,
  "cloud_artifact_exists": true
}
All capstone evidence assertions passed.

## 2. Rubric assertion summary

In [3]:
summary = json.loads((PROJECT_ROOT / 'evidence' / 'run_summary.json').read_text())
proof = pd.DataFrame(
    [{'requirement': key.replace('_', ' '), 'passed': value} for key, value in summary['proof'].items()]
)
display(proof)
assert proof['passed'].all()
print('All proof assertions:', bool(proof['passed'].all()))

                              requirement  passed
0            prompt injection was blocked    True
1                tool failure retry fired    True
2               quality replan loop fired    True
3  persistent checkpoint survived restart    True
4                     human pause resumed    True
5        output validation revision fired    True
6                          pii was masked    True
7                   structured logs exist    True
8                prometheus metrics exist    True
9                   cloud artifact exists    True

All proof assertions: True

## 3. Deliverable 1 — Agentic reasoning and real function tools

The Coordinator implements **Plan-and-Execute**. Every registered function call records a
concise **ReAct** triple: rationale/Thought, Action, and Observation. The Quality Reviewer
implements **Reflexion/self-critique**. The coordinator-to-specialist topology is
**Hierarchical Delegation**.

In [4]:
low = json.loads((PROJECT_ROOT / 'evidence' / '02_low_risk_completed.json').read_text())
tool_rows = []
observations = {o['call_id']: o for o in low['tool_observations']}
for call in low['tool_calls']:
    obs = observations[call['call_id']]
    tool_rows.append({
        'agent': call['agent'],
        'tool': call['tool_name'],
        'rationale': call['rationale'],
        'status': obs['status'],
        'latency_ms': round(obs['latency_ms'], 3),
        'observation': obs['summary'],
    })
display(pd.DataFrame(tool_rows))
print('Named reasoning patterns:', summary['reasoning_patterns'])
print('Shared state keys carried across steps:', len(low.keys()))
assert len(low['tool_calls']) >= 6
assert 'ReAct' in {d.get('pattern') for d in low['decision_trace']}

                      agent  ...                                        observation
0    Document Analyst Agent  ...  Returned object with keys: source, text, chara...
1    Document Analyst Agent  ...                                   Returned 8 items
2     Policy Research Agent  ...                                   Returned 2 items
3     Policy Research Agent  ...                                   Returned 2 items
4     Policy Research Agent  ...                                   Returned 1 items
5     Policy Research Agent  ...                                   Returned 2 items
6     Policy Research Agent  ...                                   Returned 2 items
7     Policy Research Agent  ...                                   Returned 1 items
8     Policy Research Agent  ...                                   Returned 2 items
9   Security Reviewer Agent  ...  Returned object with keys: risk_score, risk_le...
10   Artifact Storage Agent  ...  Returned object with keys: uri, metadata_uri, ...

[11 rows x 6 columns]

Named reasoning patterns: ['Plan-and-Execute', 'ReAct', 'Reflexion/self-critique', 'Hierarchical delegation']
Shared state keys carried across steps: 50

## 4. Deliverable 2 — Genuine graph orchestration with conditions and loops

The graph is built by the `transitions.Machine` framework. Conditions decide branches;
shared state is read and updated by node callbacks; three bounded cycles support tool
retry, Reflexion/re-search, and report revision.

In [5]:
graph = json.loads((PROJECT_ROOT / 'evidence' / 'graph_spec.json').read_text())
print('Framework:', graph['framework'])
print('Node count:', len(graph['nodes']))
print('Loops:')
for loop in graph['loops']:
    print(' -', loop)
edge_frame = pd.DataFrame(graph['edges'])[['trigger', 'source', 'dest', 'conditions', 'before']].fillna('')
display(edge_frame)
assert len(graph['nodes']) >= 10
assert any(edge['source'] == edge['dest'] for edge in graph['edges'])
assert any(edge.get('conditions') for edge in graph['edges'])

Framework: transitions finite-state machine
Node count: 16
Loops:
 - researching -> researching (tool retry)
 - quality_reviewed -> researching (Reflexion/re-plan)
 - output_validated -> reporting (schema-revision loop)

             trigger  ...                   before
0            advance  ...
1            advance  ...
2            advance  ...
3            advance  ...
4            advance  ...
5            advance  ...     _record_policy_retry
6            advance  ...    _mark_retry_exhausted
7            advance  ...
8            advance  ...
9            advance  ...    _record_quality_retry
10           advance  ...
11           advance  ...
12           advance  ...
13  approve_contract  ...          _apply_approval
14   reject_contract  ...         _apply_rejection
15           advance  ...
16           advance  ...  _record_report_revision
17           advance  ...   _mark_output_exhausted
18           advance  ...
19           advance  ...
20     fail_workflow  ...

[21 rows x 5 columns]

## 5. Failure paths — actual tool retry and Reflexion re-search

The first policy search deliberately raises a simulated timeout. The failed
`ToolObservation` is retained, the conditional self-loop fires, and the next attempt
succeeds. A separate quality critique routes back to research.

In [6]:
paused = json.loads((PROJECT_ROOT / 'evidence' / '03_high_risk_paused_for_human.json').read_text())
failed_tools = [o for o in paused['tool_observations'] if o['status'] == 'error']
print('Failed tool observations:', json.dumps(failed_tools, indent=2))
print('Policy retry count:', paused['policy_retry_count'])
print('Quality re-plan count:', paused['quality_retry_count'])
print('Research node visits:', paused['node_history'].count('researching'))
print('Node path:', ' -> '.join(paused['node_history']))
assert failed_tools
assert paused['policy_retry_count'] >= 1
assert paused['quality_retry_count'] >= 1
assert paused['node_history'].count('researching') >= 3

Failed tool observations: [
  {
    "call_id": "3cf44338-792f-413f-bf4a-b96ea971cfe2",
    "tool_name": "search_policy_knowledge_base",
    "status": "error",
    "summary": "ConnectionError: Simulated primary policy-index timeout for retry-path evidence",
    "output": null,
    "latency_ms": 0.07054799993966299,
    "timestamp": "2026-08-12T20:21:44.512403+00:00"
  }
]
Policy retry count: 1
Quality re-plan count: 1
Research node visits: 3
Node path: received -> guardrailed -> planned -> ingested -> researching -> researching -> analyzed -> quality_reviewed -> researching -> analyzed -> quality_reviewed -> security_reviewed -> awaiting_approval

## 6. Deliverable 3 — Multi-agent role specialization and structured communication

These are separate agent objects/classes, not personas concatenated into one prompt.
Messages contain sender, recipient, message type, content, payload, and timestamp.

In [7]:
messages = pd.DataFrame(paused['agent_messages'])
agent_summary = messages.groupby('sender').agg(
    messages=('sender', 'size'),
    recipients=('recipient', lambda values: ', '.join(sorted(set(values))))
).reset_index()
display(agent_summary)
display(messages[['sender', 'recipient', 'message_type', 'content']].tail(12))
print('Coordination strategy:', summary['coordination_strategy'])
assert messages['sender'].nunique() >= 7
assert {'sender', 'recipient', 'message_type', 'payload'}.issubset(messages.columns)

                     sender  ...                                   recipients
0  Compliance Analyst Agent  ...                       Quality Reviewer Agent
1         Coordinator Agent  ...                       Document Analyst Agent
2    Document Analyst Agent  ...                        Policy Research Agent
3      Input Security Agent  ...                            Coordinator Agent
4     Policy Research Agent  ...  Compliance Analyst Agent, Coordinator Agent
5    Quality Reviewer Agent  ...                            Coordinator Agent
6   Security Reviewer Agent  ...                            Coordinator Agent

[7 rows x 3 columns]

                      sender  ...                                            content
0       Input Security Agent  ...     Input guardrail passed; execution may proceed.
1          Coordinator Agent  ...  Plan-and-Execute plan created with seven bound...
2     Document Analyst Agent  ...         Extracted 9 clauses and contract metadata.
3      Policy Research Agent  ...        Policy tool failed; requesting graph retry.
4      Policy Research Agent  ...              Retrieved 12 policy evidence records.
5   Compliance Analyst Agent  ...  Generated 7 compliance findings from contract ...
6     Quality Reviewer Agent  ...  Evidence coverage score is 50%; re-planning ta...
7      Policy Research Agent  ...              Retrieved 14 policy evidence records.
8   Compliance Analyst Agent  ...  Generated 7 compliance findings from contract ...
9     Quality Reviewer Agent  ...  Evidence coverage score is 100%; quality gate ...
10   Security Reviewer Agent  ...  Risk classified as CRITICAL (99/100). Human ap...

[11 rows x 4 columns]

Coordination strategy: Centralized Coordinator Agent with structured specialist handoffs

## 7. Deliverable 4 — Security guardrails and structured observability

The malicious uploaded contract is inspected before the tool registry is reachable. The
output guardrail masks PII and validates a strict Pydantic schema. Monitoring is JSONL +
Prometheus, not print statements.

In [8]:
blocked = json.loads((PROJECT_ROOT / 'evidence' / '01_prompt_injection_blocked.json').read_text())
print('Attack terminal status:', blocked['status'])
print('Detected reason:', blocked['blocked_reason'])
print('Tool calls after block:', len(blocked['tool_calls']))
print('Blocked path:', ' -> '.join(blocked['node_history']))
assert blocked['status'] == 'blocked'
assert len(blocked['tool_calls']) == 0

Attack terminal status: blocked
Detected reason: ignore previous instructions; reveal system prompt; system prompt extraction
Tool calls after block: 0
Blocked path: received -> guardrailed -> blocked

In [9]:
log_path = PROJECT_ROOT / 'evidence' / 'execution_log.jsonl'
logs = [json.loads(line) for line in log_path.read_text().splitlines() if line.strip()]
log_frame = pd.DataFrame(logs)
print('Structured log events:', len(log_frame))
print('Event types:', sorted(log_frame['event'].dropna().unique()))
display(log_frame[['timestamp', 'event', 'thread_id', 'node', 'tool', 'latency_ms']].tail(15).fillna(''))

metrics_text = (PROJECT_ROOT / 'evidence' / 'metrics_before_restart.prom').read_text()
metric_names = sorted({line.split('{', 1)[0].split(' ', 1)[0] for line in metrics_text.splitlines() if line and not line.startswith('#')})
print('Prometheus metric series (sample):', metric_names[:20])
assert 'tool_call_failed' in set(log_frame['event'])
assert 'guardrail_blocked' in set(log_frame['event'])
assert 'human_interrupt' in set(log_frame['event'])
assert 'contractguard_tool_calls_total' in metrics_text

Structured log events: 195
Event types: ['agent_message', 'checkpoint_saved', 'guardrail_blocked', 'human_decision', 'human_interrupt', 'metrics_exported', 'node_completed', 'node_started', 'tool_call_completed', 'tool_call_failed', 'tool_call_started', 'workflow_retry', 'workflow_started', 'workflow_terminal']

                            timestamp  ... latency_ms
180  2026-08-12T20:21:44.716674+00:00  ...
181  2026-08-12T20:21:44.718832+00:00  ...
182  2026-08-12T20:21:44.718883+00:00  ...      2.195
183  2026-08-12T20:21:44.721531+00:00  ...
184  2026-08-12T20:21:44.721634+00:00  ...
185  2026-08-12T20:21:44.721749+00:00  ...
186  2026-08-12T20:21:44.722184+00:00  ...      0.372
187  2026-08-12T20:21:44.722330+00:00  ...
188  2026-08-12T20:21:44.722395+00:00  ...      0.725
189  2026-08-12T20:21:44.725771+00:00  ...
190  2026-08-12T20:21:44.729759+00:00  ...
191  2026-08-12T20:21:44.729896+00:00  ...
192  2026-08-12T20:21:44.730692+00:00  ...
193  2026-08-12T20:21:44.734424+00:00  ...
194  2026-08-12T20:21:44.736145+00:00  ...

[15 rows x 6 columns]

Prometheus metric series (sample): ['contractguard_active_workflows', 'contractguard_estimated_llm_cost_usd_created', 'contractguard_estimated_llm_cost_usd_total', 'contractguard_guardrail_blocks_created', 'contractguard_guardrail_blocks_total', 'contractguard_human_interrupts_created', 'contractguard_human_interrupts_total', 'contractguard_node_latency_seconds_bucket', 'contractguard_node_latency_seconds_count', 'contractguard_node_latency_seconds_created', 'contractguard_node_latency_seconds_sum', 'contractguard_node_runs_created', 'contractguard_node_runs_total', 'contractguard_retries_created', 'contractguard_retries_total', 'contractguard_tool_calls_created', 'contractguard_tool_calls_total', 'contractguard_tool_latency_seconds_bucket', 'contractguard_tool_latency_seconds_count', 'contractguard_tool_latency_seconds_created']

## 8. Deliverable 5 — Persistent checkpoint, real HITL pause/resume, and cloud artifact

A high-risk contract stops at `awaiting_approval`. The first service object is closed.
A fresh service object opens the same SQLite database, reloads the thread, applies a human
decision, and continues from the paused node.

In [10]:
loaded = json.loads((PROJECT_ROOT / 'evidence' / '04_checkpoint_loaded_after_restart.json').read_text())
final = json.loads((PROJECT_ROOT / 'evidence' / '05_high_risk_resumed_and_completed.json').read_text())
print('Node loaded after restart:', loaded['node'])
print('Interrupt payload:', json.dumps(loaded['state']['interrupt_payload'], indent=2))
print('Final status:', final['status'])
print('Human decision:', final['approval_status'], '-', final['approver'])
print('Output revision count:', final['report_revision_count'])
print('PII redactions:', final['pii_redactions'])
print('Artifact URI:', final['artifact_uri'])
assert loaded['node'] == 'awaiting_approval'
assert final['status'] == 'completed'
assert final['approval_status'] == 'approved'
assert final['report_revision_count'] >= 1
assert final['pii_redactions'] >= 3

Node loaded after restart: awaiting_approval
Interrupt payload: {
  "type": "human_approval_required",
  "thread_id": "capstone-high-risk",
  "risk_score": 99,
  "risk_level": "CRITICAL",
  "contract_value_sar": 750000.0,
  "finding_count": 7,
  "instruction": "Resume with decision=approve or decision=reject and an approver identity."
}
Final status: completed
Human decision: approved - Capstone Human Reviewer
Output revision count: 1
PII redactions: 3
Artifact URI: file:///mnt/data/contractguard-ai/evidence/artifacts/capstone-high-risk/compliance_report.md

In [11]:
cloud_files = ['Dockerfile', 'docker-compose.yml', 'deploy/prometheus.yml', 'src/contractguard/api.py']
cloud_evidence = []
for relative in cloud_files:
    path = PROJECT_ROOT / relative
    cloud_evidence.append({'artifact': relative, 'exists': path.exists(), 'bytes': path.stat().st_size if path.exists() else 0})
display(pd.DataFrame(cloud_evidence))
assert all(item['exists'] for item in cloud_evidence)

                   artifact  exists  bytes
0                Dockerfile    True    767
1        docker-compose.yml    True   1703
2     deploy/prometheus.yml    True    188
3  src/contractguard/api.py    True   2797

## 9. Final masked compliance report

In [12]:
report_path = Path(final['artifact_uri'].removeprefix('file://'))
report_text = report_path.read_text()
print(report_text[:6000])
assert '[REDACTED_EMAIL]' in report_text
assert '[REDACTED_PHONE]' in report_text
assert '[REDACTED_NATIONAL_ID]' in report_text
assert 'nora.alqahtani@example.com' not in report_text

# ContractGuard AI Compliance Report

**Report ID:** CGA-capstone-high-risk
**Thread ID:** capstone-high-risk
**Generated:** 2026-08-12T20:21:44.713989+00:00
**Vendor:** Falcon Cloud International LLC
**Contract value:** SAR 750,000.00
**Risk:** CRITICAL (99/100)
**Approval:** approved

## Executive Summary

The multi-agent audit identified 7 compliance finding(s) and assigned a CRITICAL risk rating of 99/100. The result was produced from clause extraction, policy retrieval, specialist review, security routing, and output validation rather than a single prompt.

## Compliance Findings

| ID | Severity | Topic | Finding | Policy reference |
|---|---|---|---|---|
| F-01 | HIGH | data protection | Unrestricted cross-border data transfer | Data Protection Policy — Saudi Data Residency |
| F-02 | HIGH | data protection | Subprocessor changes lack customer consent | Data Protection Policy — Saudi Data Residency |
| F-03 | HIGH | data protection | Breach notification is missing or slower than policy | Data Protection Policy — Saudi Data Residency |
| F-04 | MEDIUM | payment | Accelerated payment terms | Procurement Policy — Payment Terms |
| F-05 | HIGH | liability | Liability cap is below corporate minimum | Legal Contracting Standard — Liability and Indemnity |
| F-06 | MEDIUM | termination | Termination and renewal terms are restrictive | Legal Contracting Standard — Termination |
| F-07 | HIGH | payment | High-value procurement requires human approval | Procurement Policy — Payment Terms |

## Recommendations

1. Require Saudi data residency or a documented transfer mechanism and prior written approval.
2. Add prior notification, objection rights, and flow-down security obligations for subprocessors.
3. Require notification within 24 hours of suspected or confirmed breach discovery.
4. Change payment terms to Net 30 or longer and condition payment on accepted deliverables.
5. Increase the vendor liability cap to at least twelve months of fees, with carve-outs for privacy and security.
6. Add termination for convenience on 30 days' notice and limit automatic renewal to one-year periods.
7. Route the contract to Procurement and Legal for explicit approval before signature.

## Human Approval Record

Approved conditionally after Legal confirmed remediation of all high-severity findings.

## Evidence and Data Protection

- Policy evidence records: 14
- PII items masked: 3

## Agent Handoff Trace

- Coordinator Agent → Document Analyst Agent: Plan-and-Execute plan created with seven bounded steps.
- Document Analyst Agent → Policy Research Agent: Extracted 9 clauses and contract metadata.
- Policy Research Agent → Coordinator Agent: Policy tool failed; requesting graph retry.
- Policy Research Agent → Compliance Analyst Agent: Retrieved 12 policy evidence records.
- Compliance Analyst Agent → Quality Reviewer Agent: Generated 7 compliance findings from contract clauses and policy evidence.
- Quality Reviewer Agent → Coordinator Agent: Evidence coverage score is 50%; re-planning targeted research.
- Policy Research Agent → Compliance Analyst Agent: Retrieved 14 policy evidence records.
- Compliance Analyst Agent → Quality Reviewer Agent: Generated 7 compliance findings from contract clauses and policy evidence.
- Quality Reviewer Agent → Coordinator Agent: Evidence coverage score is 100%; quality gate passed.
- Security Reviewer Agent → Coordinator Agent: Risk classified as CRITICAL (99/100). Human approval required.
- Report Writer Agent → Output Guardian Agent: Report draft revision 0 is ready for validation.
- Output Guardian Agent → Report Writer Agent: Output schema validation failed: [{'type': 'missing', 'loc': ('recommendations',), 'msg': 'Field required', 'input': {'report_id': 'CGA-capstone-high-risk', 'thread_id': 'capstone-high-risk', 'generated_at': '2026-08-12T20:21:44.705650+00:00', 'vendor_name': 'Falcon Cloud International LLC', 'contract_value_sar': 750000.0, 'executive_summary': 'The multi-agent audit identified 7 compliance finding(s) and assigned a CRITICAL risk rating of 99/100. The result was produced from clause extraction, policy retrieval, specialist review, security routing, and output validation rather than a single prompt.', 'risk_score': 99, 'risk_level': 'CRITICAL', 'findings': [{'finding_id': 'F-01', 'topic': 'data_protection', 'title': 'Unrestricted cross-border data transfer', 'severity': 'high', 'contract_excerpt': 'the vendor may store and process all customer data outside the kingdom of saudi arabia in any jurisdiction and in global locations selected at its discretion. the vendor may appoint or replace any subprocessor without notice and without customer consent. personal data may includ…', 'policy_reference': 'Data Protection Policy — Saudi Data Residency', 'recommendation': 'Require Saudi data residency or a documented transfer mechanism and prior written approval.', 'confidence': 0.92}, {'finding_id': 'F-02', 'topic': 'data_protection', 'title': 'Subprocessor changes lack customer consent', 'severity': 'high', 'contract_excerpt': 'the vendor may store and process all customer data outside the kingdom of saudi arabia in any jurisdiction and in global locations selected at its discretion. the vendor may appoint or replace any subprocessor without notice and without customer consent. personal data may includ…', 'policy_reference': 'Data Protection Policy — Saudi Data Residency', 'recommendation': 'Add prior notification, objection rights, and flow-down security obligations for subprocessors.', 'confidence': 0.92}, {'finding_id': 'F-03', 'topic': 'data_protection', 'title': 'Breach notification is missing or slower than policy', 'severity': 'high', 'contract_excerpt': 'the vendor may store and process all customer data outside the kingdom of saudi arabia in any jurisdiction and in global locations selected at its discretion. the vendor may appoint or replace any subprocessor without notice and without customer consent. personal data may includ…',

## 10. Automated tests

The test suite covers direct/indirect injection, PII masking, real tool search, low-risk
completion, graph retry, restart persistence, HITL resume, output revision, artifact
storage, and FastAPI endpoints.

In [13]:
tests = subprocess.run(
    [sys.executable, '-m', 'pytest', '-q'],
    cwd=PROJECT_ROOT,
    text=True,
    capture_output=True,
    check=True,
    env={**os.environ, 'PYTHONPATH': str(PROJECT_ROOT / 'src')},
)
print(tests.stdout)
(PROJECT_ROOT / 'evidence' / 'pytest_results.txt').write_text(tests.stdout + tests.stderr)

........                                                                 [100%]

161

## 11. Documentation and submission completeness

- Professional README with setup, API keys, expected outputs, deployment, evidence index,
  training attribution, and SDAIA Academy link.
- Technical architecture using nodes, edges, state, agents, tools, conditions, loops, and
  checkpointers.
- Rubric traceability, security model, API reference, tests, `.gitignore`, Docker/Compose,
  CI workflow, and retained third-party license.
- Executed notebook and captured JSON/log/metric/report evidence.

The only external submission step is pushing this prepared Git repository to the
trainee's chosen GitHub repository.

In [14]:
required = [
    'README.md', '.gitignore', 'docs/architecture.md', 'docs/rubric_traceability.md',
    'docs/security.md', 'docs/api.md', 'Dockerfile', 'docker-compose.yml',
    '.github/workflows/ci.yml', 'THIRD_PARTY_NOTICES.md',
]
rows = [{'file': item, 'exists': (PROJECT_ROOT / item).exists()} for item in required]
display(pd.DataFrame(rows))
assert all(row['exists'] for row in rows)
print('Executed capstone notebook completed successfully.')

                          file  exists
0                    README.md    True
1                   .gitignore    True
2         docs/architecture.md    True
3  docs/rubric_traceability.md    True
4             docs/security.md    True
5                  docs/api.md    True
6                   Dockerfile    True
7           docker-compose.yml    True
8     .github/workflows/ci.yml    True
9       THIRD_PARTY_NOTICES.md    True

Executed capstone notebook completed successfully.